services:
  cv-landing:
    # ports:
    #   - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv-landing.entrypoints=https"
      - "traefik.http.routers.cv-landing.rule=Host(`mrussy.ru`) && PathPrefix(`/`)"
      - "traefik.http.services.cv-landing.loadbalancer.server.port=80"
      - "traefik.http.routers.cv-landing.priority=1"
      - "traefik.http.routers.cv-landing.tls.certresolver=letsEncrypt"
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: true